export const PostsFetchInitAction = 'POSTS_FETCH_INIT'
export const PostsFetchSuccessAction = 'POSTS_FETCH_SUCCESS'
export const PostsFetchNextSuccessAction = 'POSTS_FETCH_NEXT_SUCCESS'
export const PostsFetchPreviousSuccessAction = 'POSTS_FETCH_PREVIOUS_SUCCESS'
export const PostsFetchFailedAction = 'POSTS_FETCH_FAILED'